# Generated by Django 5.1.7 on 2025-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
