from django.urls import path
from . import views  

urlpatterns = [
    path('', views.main, name='main'), 
    path('news/', views.news, name='news'),     
    path('about/', views.about, name='about'),  
    path('links/', views.links, name='links'),
    path('pool/', views.pool, name='pool'),
    path('create', views.create, name='create'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_, name='logout'),
    path('detail/<int:pk>/', views.detail, name='detail_news'),
    path('admin/', views.admin, name="admin"),
    path('update/<int:pk>/', views.update_news, name='update_news'),
    path('delete_news/<int:pk>/', views.delete_news, name='delete_news'),
    path('video/', views.videopost, name='videopost'),
    path('products/', views.products, name='products'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<int:pk>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-success/<int:order_id>/', views.order_success, name='order_success'),
    path('create-product/', views.create_product, name='create_product'),
    path('orders/', views.order_history, name='order_history'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('all-orders/', views.all_orders, name='all_orders'),
    path('purchase-history/', views.my_purchase_history, name='my_purchase_history'),
    path('manager-dashboard/', views.manager_dashboard, name='manager_dashboard'),
    path('change-order-status/<int:order_id>/', views.change_order_status, name='change_order_status'),
    path('user-purchase-history/<int:user_id>/', views.user_purchase_history, name='user_purchase_history'),
]